### ISSUE TITLE
limited measuring

### ISSUE THREAD

**Issue by eboyid** [kurimawxx00/hx710B_pressure_sensor#1]
Hi. I used the same module to measuring the air pressure. But it measuring untill 101.5 mmHg. While I read the spec that the module could read until 40kPa. Which mean about 300mmHg. Could you assist me to fix tis stuff, hhe.

Anw, thank you for your custom this Lib. so much help ..

**Comment by kurimawxx00** [comment]
Edited formula, please use updated library
